import { h, time, dateLabel, badge } from '../lib/format.js';
export function proposalPanel(state) {
  const p = state.proposal;
  if (!p) return `<section class="panel proposal-panel"><div class="panel-head"><div><h2>Schedule proposal</h2><p>The engine calculates. The officer decides.</p></div></div><div class="empty"><div class="empty-symbol">01</div><strong>Ready to repair the plan</strong><p>Generate a proposal to allocate pending requests around the locked bookings.</p><button class="button primary" data-action="generate">Generate proposal <span aria-hidden="true">&rarr;</span></button></div></section>`;
  const stale = p.planning_version !== state.snapshot.metadata.planning_version;
  const valid = !!p.allocations?.length;
  const committed = p.status_workflow === 'committed';
  const engine=p.engine==='cp_sat'?'OR-Tools CP-SAT':p.engine==='manual'?'Manual plan / independent checker':'Tiny-demo search (not CP-SAT)';
  const changes=valid?`<div class="proposal-changes">${(p.changes||[]).map((c)=>`<div class="proposal-change ${c.removed?'removed':''}"><div><b>${h(c.request_id)}</b> <span>${h(c.title)}</span></div>${c.removed?`<div class="change-times"><span class="old-time">${dateLabel(c.start)} ${time(c.start)} - ${time(c.end)}</span><span>&rarr;</span><strong>Approved pool</strong></div><small>Removed from schedule when this proposal is published</small>`:`<div class="change-times"><span class="old-time">${dateLabel(c.preferred_start)} ${time(c.preferred_start)}</span><span>&rarr;</span><strong>${dateLabel(c.start)} ${time(c.start)} - ${time(c.end)}</strong></div><small>${h(c.engineer_id)} &middot; ${c.locked?'locked manual position':'solver may reposition until published'}</small>`}</div>`).join('')}</div>`:'';
  return `<section class="panel proposal-panel"><div class="panel-head"><div><h2>Schedule proposal</h2><p>${h(p.id||'Not staged')} &middot; input revision ${h(p.planning_version||state.snapshot.metadata.planning_version)}</p></div>${badge(stale?'STALE':p.status,stale?'warning':valid?'success':'warning')}</div><div class="proposal-body"><div class="proposal-info"><div class="engine-label">${h(engine)} &middot; ${Number(p.elapsed_seconds).toFixed(3)}s</div><p class="muted">${h(p.message)}</p>${stale?'<div class="notice warning">Planning inputs changed. Generate a new proposal before publishing.</div>':''}</div><div class="proposal-actions">${changes}${valid?`<div class="validation-note">Independent checker passed. This is not railway access authority.</div><button class="button primary full" data-action="commit" ${stale||committed?'disabled':''}>${committed?'Published':'Approve & publish'}</button>`:''}<button class="button quiet full" data-action="generate">Auto-fit unlocked jobs again</button></div></div></section>`;
}
