import { h, time, badge } from '../lib/format.js';
import { timeline, corridor } from '../components/timeline.js';
import { conflictPanel } from '../components/conflicts.js';
import { proposalPanel } from '../components/proposal.js';
import { requestTable } from './requester.js';

export function officerPage(state) {
  const s=state.snapshot;
  return `<div class="stats-grid"><div class="stat"><span>Pending requests</span><strong>${s.requests.filter(r=>r.status==='submitted').length}</strong><small>Not yet reserved</small></div><div class="stat"><span>Committed bookings</span><strong>${s.committed_allocations.length}</strong><small>Locked in this starter</small></div><div class="stat ${state.issues.length?'stat-warning':''}"><span>Requested-plan issues</span><strong>${state.issues.length}</strong><small>Across time, space and resources</small></div><div class="stat"><span>Engineering window</span><strong class="stat-time">01:00 - 04:30</strong><small>Fictional fixture / SGT</small></div></div>${corridor(s)}<div class="workspace-grid"><div class="workspace-main">${timeline(state)}${requestTable(s)}</div><aside>${conflictPanel(state.issues)}${proposalPanel(state)}</aside></div>`;
}

export function resourcesPage(state) {
  const s=state.snapshot;
  return `<div class="notice neutral">Every resource change increments the planning revision. Existing proposals then need to be regenerated. A change can invalidate a locked booking; the system will flag it, not move it silently.</div><section class="panel"><div class="panel-head"><div><h2>Engineer catalog</h2><p>Qualifications and unavailable intervals</p></div>${state.config.auth_mode==='demo'?'<button class="button secondary small" data-action="absence">Demo: E01 unavailable after 02:20</button>':''}</div><div class="table-scroll"><table><thead><tr><th>Engineer</th><th>Skill</th><th>Unavailable periods</th></tr></thead><tbody>${s.engineers.map(e=>`<tr><td><strong>${h(e.id)}</strong><span class="cell-sub">${h(e.name)}</span></td><td>${e.skills.map(x=>badge(x)).join(' ')}</td><td>${e.unavailable.length?e.unavailable.map(w=>`${h(w.start.slice(0,10))} ${time(w.start)} - ${time(w.end)}`).join('<br>'):'None recorded'}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>Equipment catalog</h2><p>One physical unit per equipment ID</p></div></div><div class="table-scroll"><table><thead><tr><th>Equipment</th><th>Type</th><th>State</th><th>Action</th></tr></thead><tbody>${s.equipment.map(q=>`<tr><td><strong>${h(q.id)}</strong></td><td>${h(q.type.replaceAll('_',' '))}</td><td>${badge(q.serviceable?'Serviceable':'Out of service',q.serviceable?'success':'warning')}</td><td><button class="button secondary small" data-equipment="${h(q.id)}" data-serviceable="${!q.serviceable}">${q.serviceable?'Mark unavailable':'Restore'}</button></td></tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><p>Local audit trail</p></div></div><div class="audit-list">${state.audit.map(a=>`<div><span>${h(a.action.replaceAll('_',' '))}</span><small>${h(a.actor)} &middot; ${h(a.detail)}</small></div>`).join('')}</div></section>`;
}
