import { h, time, badge, duration } from '../lib/format.js';
import { timeline, weekOverview } from '../components/timeline.js?v=20260910-demo2';

function requestPool(state){
  const scheduled=new Set((state.manualPlan||[]).map(a=>a.request_id));
  const jobs=state.snapshot.requests.filter(r=>r.status==='submitted'||(['approved','scheduled'].includes(r.status)&&!scheduled.has(r.id)));
  const selected=state.selectedPool;
  const approved=r=>r.status!=='submitted';
  const approvedJobs=jobs.filter(approved);
  return `<section class="panel request-pool" data-pool-drop><div class="pool-head"><div><h2>Request pool</h2><span>${jobs.filter(r=>!approved(r)).length} Unapproved &middot; ${approvedJobs.length} Approved</span></div>${jobs.length?`<div class="pool-actions"><button class="button primary small" data-action="add-to-schedule" ${approvedJobs.length?'':'disabled'}>Add to schedule</button>${selected.size?`<div class="selection-actions"><b>${selected.size} selected</b><button class="button quiet-action" data-action="select-all-pool">Select all</button><button class="button secondary small" data-action="unapprove-selected">Unapprove</button><button class="button primary small" data-action="approve-selected">Approve</button><button class="icon-button" data-action="clear-pool-selection" aria-label="Clear selection">&times;</button></div>`:''}</div>`:''}</div><div class="pool-grid">${jobs.length?jobs.map(r=>`<article class="pool-job ${approved(r)?'approved':'submitted'}"><label class="hover-select"><input type="checkbox" data-select-pool="${h(r.id)}" ${selected.has(r.id)?'checked':''}/><span class="sr-only">Select ${h(r.id)}</span></label><div class="pool-job-top"><strong>${h(r.id)}</strong>${badge(approved(r)?'Approved':'Unapproved',approved(r)?'success':'warning')}</div><h3>${h(r.title)}</h3><div class="job-facts"><span>${h(r.work_sector)}</span><span>${duration(r)} min</span><span>${h(r.required_skill)}</span><span>${h(r.power_requirement)}</span></div></article>`).join(''):'<div class="empty compact-empty"><span class="clear-mark">&#10003;</span><strong>No requests remaining</strong></div>'}</div></section>`;
}

export function officerPage(state) {
  const s=state.snapshot;
  const pending=s.requests.filter(r=>r.status==='submitted').length;
  const manualLocks=(state.manualPlan||[]).filter(a=>a.locked&&!s.committed_allocations.some(c=>c.request_id===a.request_id)).length;
  const conflictIds=new Set(state.issues.flatMap(issue=>issue.request_ids||[])),conflicts=conflictIds.size?Math.max(1,conflictIds.size-1):state.issues.length;
  return `<div class="schedule-page">${weekOverview(state)}${timeline(state,{editable:true})}${requestPool(state)}${state.issues.length?`<div class="conflict-toast"><b>!</b><span>${conflicts} schedule conflict${conflicts===1?'':'s'}</span></div>`:''}</div>`;
}

export function resourcesPage(state) {
  const s=state.snapshot;
  return `<div class="notice neutral">Every resource change increments the planning revision. Existing proposals then need to be regenerated. A change can invalidate a locked booking; the system will flag it, not move it silently.</div><section class="panel"><div class="panel-head"><div><h2>Engineer catalog</h2><p>Qualifications and unavailable intervals</p></div>${state.config.auth_mode==='demo'?'<button class="button secondary small" data-action="absence">Demo: E01 unavailable after 02:20</button>':''}</div><div class="table-scroll"><table><thead><tr><th>Engineer</th><th>Skill</th><th>Unavailable periods</th></tr></thead><tbody>${s.engineers.map(e=>`<tr><td><strong>${h(e.id)}</strong><span class="cell-sub">${h(e.name)}</span></td><td>${e.skills.map(x=>badge(x)).join(' ')}</td><td>${e.unavailable.length?e.unavailable.map(w=>`${h(w.start.slice(0,10))} ${time(w.start)} - ${time(w.end)}`).join('<br>'):'None recorded'}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>Equipment catalog</h2><p>One physical unit per equipment ID</p></div></div><div class="table-scroll"><table><thead><tr><th>Equipment</th><th>Type</th><th>State</th><th>Action</th></tr></thead><tbody>${s.equipment.map(q=>`<tr><td><strong>${h(q.id)}</strong></td><td>${h(q.type.replaceAll('_',' '))}</td><td>${badge(q.serviceable?'Serviceable':'Out of service',q.serviceable?'success':'warning')}</td><td><button class="button secondary small" data-equipment="${h(q.id)}" data-serviceable="${!q.serviceable}">${q.serviceable?'Mark unavailable':'Restore'}</button></td></tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><p>Local audit trail</p></div></div><div class="audit-list">${state.audit.map(a=>`<div><span>${h(a.action.replaceAll('_',' '))}</span><small>${h(a.actor)} &middot; ${h(a.detail)}</small></div>`).join('')}</div></section>`;
}
