// Run with node scripts/check-ui-demo.mjs. No server or browser data is modified.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const fixture=JSON.parse(await readFile(new URL('../frontend/demo-snapshot.json',import.meta.url)));
const storage=new Map();
globalThis.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};
globalThis.fetch=async()=>({ok:true,json:async()=>structuredClone(fixture)});
const {demoApi}=await import('../frontend/src/lib/demo-api.js');
const call=(path,body,user='demo-officer')=>demoApi(path,{body},user);
let s=await call('/planning-snapshot');
assert.equal(s.requests.length,12);assert.equal(s.committed_allocations.length,8);
const track=await call('/planning-snapshot',undefined,'demo-track');
assert.ok(track.requests.length>0);assert.ok(track.requests.every(r=>r.owner_id==='demo-track'));
const plan=structuredClone(s.committed_allocations);plan[2].start='2026-09-14T03:05:00+08:00';
await call('/schedule/check',{allocations:plan});
assert.equal((await call('/planning-snapshot')).demo_draft[2].start,plan[2].start);
await call('/requests/approval',{request_ids:['R11'],approved:true});
await call('/allocations/locks',{request_ids:['R03'],locked:true});
s=await call('/planning-snapshot');
assert.equal(s.requests.find(r=>r.id==='R11').status,'approved');
assert.equal(s.committed_allocations.find(a=>a.request_id==='R03').locked,true);
const p=await call('/schedule/proposals',{locked_allocations:[plan[0]]});
assert.equal(p.allocations.find(a=>a.request_id==='R01').start,plan[0].start);
await call(`/proposals/${p.id}/commit`,{expected_version:p.planning_version});
assert.equal((await call('/planning-snapshot')).committed_allocations.length,11);
const created=await call('/requests',{...track.requests[0],title:'UI test request'},'demo-track');
await call(`/requests/${created.id}/cancel`,{},'demo-track');
assert.equal((await call('/planning-snapshot',undefined,'demo-track')).requests.find(r=>r.id===created.id).status,'cancelled');
await assert.rejects(()=>call('/requests/approval',{request_ids:['R12'],approved:true},'demo-track'),/officer/);
await call('/demo/reset');
s=await call('/planning-snapshot');assert.equal(s.requests.length,12);assert.equal(s.committed_allocations.length,8);assert.equal(s.demo_draft,undefined);
console.log('UI demo checks passed: seed, roles, draft persistence, approval, locks, preset, save, request, withdraw, reset.');
